### ISSUE TITLE
WordPress

### ISSUE THREAD

**Issue by jasontucker** [smadeira/ministry-platform-api#1]
I noticed some of your projects are built to be used with WordPress, have you made this library setup for WordPress use?

I'm building an intranet using WordPress and I wanted to list all of the birthdays our staff for this month and the upcoming month, I have a group with the staff in them I just need to look up their birthdays from their contact record and list their name and birthday. Where should I start with this?

**Comment by smadeira** [comment]
It isn't setup as a WP plugin but I am using it on our web site as a
plugin.  I pull the code down locally, use composer to update it and grab
the dependencies, write the actual wp-specific code like shortcodes, etc.
and then push the whole thing up to WP as a plugin and activate it.  No
fancy interface in admin or anything like that.  Just code that runs.  For
my needs that has worked and I haven't had to learn much WP (which is a
bonus.)

-------------------------------------------------
Scott Madeira

**Comment by jasontucker** [comment]
Do you by chance have any code you'd be will to share as a gist? I'm just getting my feet wet with using an API and doing so with WordPress so anything you can share would be greatly appreciated.

**Comment by smadeira** [comment]
You can check this out https://github.com/smadeira/mp-wordpress-plugin  I put it together to try and integate the API into our wordpress site.  It will get you started.  I am NOT a WordPress developer so there may be numerous issues with the code but it does work.  Hope that helps.
