### ISSUE TITLE
Server Side Filtering

### ISSUE THREAD

**Issue by Cdrew92** [smadeira/ministry-platform-api#10]
Hey Scott,

We touched on a similar topic on the MP forum, but do you have any plans to implement server side filtering in the wrapper?

EX: https://github.com/faithchapel/mp-rest-documentation#get-a-filtered-list
tables/contacts?$Filter=Last_Name='Administrator'

Currently I'm sending a query from the API Wrapper such as the one below, and filtering client side:
```
Route::get('/ministries', function () {
    $mp = new \MinistryPlatformAPI\MinistryPlatformTableAPI();
    $mp->authenticate();
    $ministries = $mp->table('Ministries')->select('Ministries.[Ministry_ID] AS [Ministry ID], 
    Ministries.[Ministry_Name] AS [Ministry Name]'
    )->get();
    return response()->json([$ministries]);
});
```

**Comment by cscprof** [comment]
There is a filter() method in the API that uses the same MP "SQL"  Here is an example query we use for our calendar. Is thgis what you are looking for?

```
$filter = "Events.Event_Start_Date between '" . $firstOfMonth . "' AND '" . $endDate . "' 
AND Visibility_Level_ID_Table.[Visibility_Level_ID] = 4 
AND Event_Type_ID_Table.[Event_Type_ID] IN (1,7,14,15,19,21) 
AND Events.[_Approved] = 1 
AND ISNULL(Events.[Cancelled], 0) = 0";


$event = $mp->table('Events')
        ->select("Event_ID, Event_Title, Event_Start_Date, Event_End_Date, Meeting_Instructions, Events.Description, 
Location_ID_Table.[Location_Name], Event_Type_ID_Table.[Color], Registration_Active, Registration_Start,
 Registration_End, Online_Registration_Product, External_Registration_URL, dp_fileUniqueId AS Image_ID")
        ->filter($filter)
        ->orderBy('Event_Start_Date')
        ->get();
```

**Comment by Cdrew92** [comment]
I was looking for a way to filter the API data dynamically.

So for example my first API call when a user loads the /events page would be ```GET apiwrapper.org/events```, which would load all the events from MP. 

Now if the user selects "Students" from a dropdown filter, I would then want to call the API with something like ```GET apiwrapper.org/events?filter&ministry_type=students``` to only load events that have ```Ministry_Type = Students```

**Comment by cscprof** [comment]
I have no plans to implement that in the API Wrapper.  To me that is application specific code that you would implement as needed. When you get the filter info in the query string you would adjust your API filter() clause and do a new query.  Or, use cached data if you have it.

**Comment by Cdrew92** [comment]
Here's where I landed:

import ```request``` middleware:
```use Illuminate\Http\Request;```

The query parameter in the GET request can be formatted like so, adding all filter arguments into the filter[] array:
```
https://myapiwrapper.org/events?filter[]=Congregation_ID=1&filter[]=Event_End_Date%3EGETDATE()&filter[]=Cancelled=0&filter[]=Visibility_Level_ID%20BETWEEN%203%20AND%204&filter[]=[_Approved]=1
```
OR it can be formatted while only instantiating the filter[] array once:
```
https://myapiwrapper.org/events?filter%5B%5D=Congregation_ID%20%3D%201%20AND%20Event_End_Date%20%3E%20GETDATE()%20AND%20Cancelled%20%3D%200%20AND%20Visibility_Level_ID%20BETWEEN%203%20AND%204%20AND%20%5B_Approved%5D%20%3D%201
```

Define route, and check for filter parameter in query string:
```
Route::get('/events', function (Request $request) {
    $mp = new \MinistryPlatformAPI\MinistryPlatformTableAPI();
    $mp->authenticate();
//check for filter query param in request
    if( $request->has('filter') ) {
        $filterArray =  $request->query('filter');
        $filterString = implode(" AND ", $filterArray);
    } else {
        $filterString = "Congregation_ID = 1 AND Event_End_Date > GETDATE() AND Cancelled = 0 AND Visibility_Level_ID BETWEEN 3 AND 4 AND [_Approved] = 1";
    }
    $events = $mp->table('Events')->select('*, dp_fileUniqueId AS FileID')->filter("$filterString")->orderBy('Event_Start_Date ASC')->get();
    return response()->json([$events]);
});
```
