### ISSUE TITLE
having trouble getting authentication to pass: "<url> malformed"

### ISSUE THREAD

**Issue by chancesmith** [smadeira/ministry-platform-api#3]
I'm having issues with authentication.

We this error: `Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Thinking it authinication because...

During `$mp->authenticate();` the `getToken()` method calls the `$this->parseTokenResponse($response);` where the `$body` is resulting in null.

Is this issue with my `.env` variables?

**Comment by chancesmith** [comment]
Nvm, I had the wrong discovery endpoint from MP. Thank you!

**Comment by MACscr** [comment]
I am getting the exact same error. How do we find these 3 paths and is the MP_OAUTH_REDIRECT_URL required and what is it used for?

They really make this overcomplicated. Just let me use curl and a username/password and call it a day.

**Comment by MACscr** [comment]
Nevermind, seems the docs are wrong again here and the discovery endpoint should more like 

https://platform-hostname/ministryplatformapi/oauth/.well-known/openid-configuration

**Comment by smadeira** [comment]
MP_OAUTH_DISCOVERY_ENDPOINT="https://connect.example.com/ministryplatform/oauth"
This is correct on my installation and is what MP documentation tells us to use.

The MP_OAUTH_REDIRECT_URL="https://example1.com/oAuth" this is used when you are using the authorization code grant type.
