### ISSUE TITLE
autoload

### ISSUE THREAD

**Issue by MACscr** [smadeira/ministry-platform-api#4]
When installing your package in its own directory using 'composer require smadeira/ministry-platform-api', it seems to create all the proper packages, but your class cant be loaded with autoload as your documents suggests. It cant find the class. If everything is default, I would think it would work. The generated composer.json in the root directory where the command was run just has:

```
{
    "require": {
        "smadeira/ministry-platform-api": "^2.3"
    }
}
```

and using:

```
require_once __DIR__ . '/vendor/autoload.php';

use MinistryPlatformAPI\MinistryPlatformAPI as MP;

......
```

Results in: 

```
PHP Fatal error:  Uncaught Error: Class 'MinistryPlatformAPI\MinistryPlatformAPI' not found in /var/www/html/api/mp.php:12
Stack trace:
#0 {main}
```

I know i could manually require the needed file, but was wondering why the autoload isnt working by default.

**Comment by MACscr** [comment]
nevermind, appears to be a typo in your readme example. Should be 

`use MinistryPlatformAPI\MinistryPlatformTableAPI as MP;`

**Comment by smadeira** [comment]
My apologies of the docs.  I updated the top of the page but missed the udpate for the "full example code" in the middle.  Sorry for the confusion and thanks for pointing it out.  I will push an update now.
