### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by oneseventeen** [smadeira/ministry-platform-api#7]
I've started developing my apps in Laravel 6, which requires newer versions of illuminate than your API supports.  Would it be possible to also allow illuminate 6.x?

I think changing the illuminate requirements to the following is all that is required (but I don't know much about Composer, so I could be causing other problems down the road):
```
        "illuminate/cache": "5.x||6.x",
        "illuminate/filesystem": "5.x||6.x",
        "illuminate/container": "5.x||6.x",
```

I've made a local copy of your package and installed it via composer without any issues, but I imagine you have more things you could test.

**Comment by smadeira** [comment]
I updated composer.json as suggested and it seems to work just fine.  If you find something that doesn't work, let me know and I'll have a look at it.
