### ISSUE TITLE
Uploading images?

### ISSUE THREAD

**Issue by MACscr** [smadeira/ministry-platform-api#8]
I apologize, but how should I go about uploading an image that will be associated with lets say a Sermon?

$rec[] = ['TableName' => 'Pocket_Platform_Sermons', 'RecordId' => (int)$sermon_id];

I really dont even know where to start.

**Comment by smadeira** [comment]
Hey Mark,

The current API only supports the Tables and Procedures end points.  It
does not support file uploads as I haven't had a need for it.

But, if you give me a week or two, I'll see if I can get the Files piece
working to support the basic features.

-------------------------------------------------
Scott Madeira

**Comment by MACscr** [comment]
Well I extended the library to be able to do it but its a bit dirty (works though). The problem I am finding is that for the extra parameter options:

```
[
  {
    "FileId": 0,
    "FileName": "string",
    "Description": "string",
    "FileSize": 0,
    "ImageHeight": 0,
    "ImageWidth": 0,
    "IsDefaultImage": true,
    "TableName": "string",
    "RecordId": 0,
    "UniqueFileId": "string",
    "LastUpdated": "2020-05-05T18:12:24.339Z"
  }
]
````

They have to be passed as form_params with guzzle and when using multipart for the image data, you cant use anything other than multipart for that call. 

http://docs.guzzlephp.org/en/stable/request-options.html#multipart

> multipart cannot be used with the form_params option. You will need to use one or the other. Use form_params for application/x-www-form-urlencoded requests, and multipart for multipart/form-data requests.
> 
> This option cannot be used with body, form_params, or json

Now I really only need IsDefaultImage and that can be passed in the url as '?%24default=true' (not sure why they change the variable name). Id like to know what the UniquFileID is. Wondering if I can set that to something unique and new files will overwrite that file record without having to actually know the file record. Right now if I do multiple test uploads to a a sermon, it creates multiple files all with them saying they are the default image. 

I had quite a few issues with the headers and the additional curl parameters, so had to remove them and reformat. Here is what I have so far that does at least successfully upload and attach  a sermon. Obviously not that flexible and as mentioned, a bit crude.

```
// Attempt to authenticate to the MP API
$mp = new FILES();
$mp->authenticate();

$response = $mp->table('Pocket_Platform_Sermons')
            ->record($record_id)
            ->file($filePath)
            ->upload();

var_dump($response[0]);
```

```
<?php namespace MinistryPlatformAPI;


class MinistryPlatformFilesAPI extends MinistryPlatformBaseAPI
{

    /**
     *  parameters
     *
     */
    protected $tableName = null;
    protected $recordID = null;
    protected $filePath = null;

    /**
     * Set the table for the GET request
     *
     * @param $tableName
     *
     * @return $this
     */
    public function table($tableName)
    {
        $this->tableName = $tableName;

        return $this;
    }

    /**
     * Set the recordID for
     *
     * @param $recordID
     *
     * @return $this
     */
    public function record($recordID)
    {
        $this->recordID = $recordID;

        return $this;
    }

    /**
     * Set the filePath for
     *
     * @param $filePath
     *
     * @return $this
     */
    public function file($filePath)
    {
        $this->filePath = $filePath;

        return $this;
    }

    /**
     * upload the file
     *
     * @return mixed
     */
    public function upload()
    {
        // Set the header
        $this->buildHttpHeader();

        $parameters = [
            'multipart' => [
              [
                'name' => 'image',
                'contents' => fopen($this->filePath, 'r'),
              ]
            ],
            'headers' => $this->headers,
        ];

        return  $this->sendData('POST', $parameters);
    }

    /**
     * Construct the API Endpoint for the request
     *
     * @return string
     */
    protected function buildEndpoint()
    {
        return $this->authorization->apiEndpoint . '/files/' . $this->tableName . '/' . $this->recordID.'?%24default=true';
    }

    protected function buildHttpHeader()
    {
        // Set the header
        $this->headers = [
            'Accept' => 'application/json',
            'Authorization' => $this->authorization->credentials->getAccessToken()
          ];

        return $this->headers;
    }

    /**
     * Return a Guzzle error message
     */
    public function errorMessage()
    {
        return $this->errorMessage;
    }
}
```

Here is what the API looks like in swagger:

![image](https://user-images.githubusercontent.com/1404944/81107278-e8f0bc00-8ee4-11ea-9590-d3cdee9561ea.png)

**Comment by smadeira** [comment]
API wrapper now supports Files endpoint.
